# Generated by Django 3.2 on 2021-04-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_postedv',
            new_name='date_posted',
        ),
    ]
